spring:
  datasource:
    url: jdbc:postgresql://ec2-23-23-220-163.compute-1.amazonaws.com:5432/d2k43n3umfu2jb
    username: xqytjdhpmaiqmo
    password: 20ba9f5b95026caf247dec2260f69677bb93cba32d0a89c56a5cebec141d3de0

server:
  port: 3000

github:
  client:
    clientId: 0943fe6f4ea2acc144fe
    clientSecret: 963a196934184782f7af4f8a5b9c3a638b1ce714
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

facebook:
  client:
    clientId: 850542525120173
    clientSecret: f68d441316b43d4972ac39e7674e3571
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

google:
  client:
    clientId: 580814425439-lbjm6ir57cd7u0spvms1fe8rbg5vrpsa.apps.googleusercontent.com
    clientSecret:  0Dx_fbJ4Mov6jjH9Od506uAg
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope: email
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo